[package]
name = "gifzo_rust_server"
version = "0.1.0"
authors = ["Koji.Ota"]

[dependencies]
staticfile = "0.2.0"
mount = "0.1.0"
iron = "0.3.0"

[dependencies.multipart]
version = "0.7"
default-features = false
features = ["server", "iron"]
